dist: trusty
language: cpp
script: cmake

sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - g++-5
      - g++-5-multilib
      - g++-multilib
      - libhdf5-dev
      - libhdf5-serial-dev
      - libboost-thread1.55-dev
      - libboost-system1.55-dev
      - libboost-date-time1.55-dev
      - libboost-chrono1.55-dev
      - libboost-python1.55-dev
      - qtbase5-dev
      - libqt5xmlpatterns5-dev
      - libqt5opengl5-dev

matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: gcc-5
      script:
        - mkdir build
        - cd build
        - ../linux_install_dependencies.sh
        - cmake ../src/
        - make -j2
