image: Visual Studio 2015

matrix:
  fast_finish: true

platform:
#  - Win32
  - x64

configuration:
  - Debug
#  - Release

build_script:
  - call windows_build.bat %configuration% %platform%

build:
  parallel: true

test: off