IF ( WIN32 )
  SET ( WIN32_STYLE_FIND 1 )
ENDIF ()
IF ( MINGW )
  SET( WIN32_STYLE_FIND 0 )
  SET( UNIX_STYLE_FIND 1 )
ENDIF ()
IF ( UNIX )
  SET ( UNIX_STYLE_FIND 1 )
ENDIF ()

IF ( UNIX_STYLE_FIND )
  FIND_PATH ( OpenGM_INCLUDE_DIR opengm/opengm.hxx )
  INCLUDE ( FindPackageHandleStandardArgs )
  FIND_PACKAGE_HANDLE_STANDARD_ARGS ( OpenGM DEFAULT_MSG OpenGM_INCLUDE_DIR )
ELSEIF ( WIN32_STYLE_FIND )
  FIND_PATH ( OpenGM_INCLUDE_DIR opengm/opengm.hxx
    PATHS
      C:/opengm-2.3.3 )
  INCLUDE ( FindPackageHandleStandardArgs )
  FIND_PACKAGE_HANDLE_STANDARD_ARGS ( OpenGM DEFAULT_MSG OpenGM_INCLUDE_DIR )
ENDIF ()

