#! /usr/bin/env python2.7
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import argparse
import numpy as np
import matplotlib.image as mpimg
import matplotlib.pyplot as plt

def usage():

	print("Author: Mykyta Fastovets / CVSSP / Athpose3D project / 2010")
	print("This code plots similarity matrix (generated by poseGui)")
	print("Example: ./plotSimilarityMatrix.py trijumpSD.ism")


parser = argparse.ArgumentParser(description='Example with non-optional arguments')

parser.add_argument('filename', action="store")

maximum = 3*255**2

fig = plt.figure()

parseResult = parser.parse_args()
data0 = [line.strip().split() for line in open(parseResult.filename)]
data = [map(float, x) for x in data0]
newData = []

numFrames=int(data[0][0])

data.pop(0)

newData=[]
for i in range(numFrames):
	newData.append(data[i])

mean = np.mean(newData)
#print mean

plotData=[]
for line in newData:

	newLine=[]
	for element in line:
		#print element
		if element==0.0:
			#print element
			element=mean
		newLine.append(element)

	plotData.append(newLine)

#print newData

npArr = np.array(plotData)

plt.subplot(1, 2, 1)
plt.imshow(npArr, interpolation='none')
#plt.plot(npArr[0,:],npArr[:,0],'r+')
plt.title(parseResult.filename)
# set the limits of the plot to the limits of the data
plt.colorbar()

ax = plt.subplot(1, 2, 2)
numBins = 50

histData=[]

print newData

for line in newData:
	for element in line:
		if element != 0:
			histData.append(element)

ax.hist(histData, numBins, alpha=0.8)

plt.show()